const mongoose = require("mongoose");
const Inventory = require("../models/Inventory");
require("dotenv").config({ path: "./config/config.env" });

// Additional inventory categories for FireLink SL
// Starting item_ID from 2001 to avoid conflicts with existing data (1001-1023)
const newCategoryItems = [
  // ========== VEHICLES (Max: 5 units) ==========
  {
    item_ID: 2001,
    item_name: "Fire Engine - Pumper Type 1",
    category: "Vehicles",
    quantity: 3,
    condition: "Good",
    location: "Main Station - Vehicle Bay 1",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2002,
    item_name: "Aerial Ladder Truck - 100ft",
    category: "Vehicles",
    quantity: 2,
    condition: "Good",
    location: "Main Station - Vehicle Bay 2",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2003,
    item_name: "Rescue Ambulance - Advanced Life Support",
    category: "Vehicles",
    quantity: 4,
    condition: "Good",
    location: "Main Station - Vehicle Bay 3",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2004,
    item_name: "Heavy Rescue Vehicle - Type 2",
    category: "Vehicles",
    quantity: 2,
    condition: "Good",
    location: "Main Station - Vehicle Bay 4",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2005,
    item_name: "Water Tanker - 5000 Gallon",
    category: "Vehicles",
    quantity: 2,
    condition: "Good",
    location: "Main Station - Vehicle Bay 5",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2044,
    item_name: "Fire Engine - Pumper Type 2",
    category: "Vehicles",
    quantity: 3,
    condition: "Good",
    location: "Main Station - Vehicle Bay 6",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2045,
    item_name: "Brush Truck - Wildland",
    category: "Vehicles",
    quantity: 2,
    condition: "Good",
    location: "Main Station - Vehicle Bay 7",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2046,
    item_name: "Hazmat Response Unit",
    category: "Vehicles",
    quantity: 1,
    condition: "Good",
    location: "Main Station - Vehicle Bay 8",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2047,
    item_name: "Command Vehicle - Mobile",
    category: "Vehicles",
    quantity: 2,
    condition: "Good",
    location: "Main Station - Vehicle Bay 9",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2048,
    item_name: "Utility Truck - Personnel Transport",
    category: "Vehicles",
    quantity: 3,
    condition: "Good",
    location: "Main Station - Vehicle Bay 10",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2049,
    item_name: "Aerial Platform - 75ft",
    category: "Vehicles",
    quantity: 1,
    condition: "Good",
    location: "Main Station - Vehicle Bay 11",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2050,
    item_name: "Foam Unit - Airport Style",
    category: "Vehicles",
    quantity: 1,
    condition: "Good",
    location: "Main Station - Vehicle Bay 12",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2051,
    item_name: "Quick Response Vehicle - SUV",
    category: "Vehicles",
    quantity: 4,
    condition: "Good",
    location: "Main Station - Vehicle Bay 13",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2052,
    item_name: "Rescue Ambulance - Basic Life Support",
    category: "Vehicles",
    quantity: 3,
    condition: "Good",
    location: "Main Station - Vehicle Bay 14",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2053,
    item_name: "Tender Truck - Water Supply",
    category: "Vehicles",
    quantity: 2,
    condition: "Good",
    location: "Main Station - Vehicle Bay 15",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },

  // ========== HEAVY EQUIPMENT (Max: 10 units) ==========
  {
    item_ID: 2006,
    item_name: "Water Pump - Portable 1500 GPM",
    category: "Heavy Equipment",
    quantity: 6,
    condition: "Good",
    location: "Main Station - Equipment Room C",
    status: "Available",
    threshold: 2,
    expire_date: null,
  },
  {
    item_ID: 2007,
    item_name: "Generator - Diesel 10KW",
    category: "Heavy Equipment",
    quantity: 8,
    condition: "Good",
    location: "Main Station - Equipment Room C",
    status: "Available",
    threshold: 2,
    expire_date: null,
  },
  {
    item_ID: 2008,
    item_name: "Hydraulic Rescue Tools - Jaws of Life",
    category: "Heavy Equipment",
    quantity: 4,
    condition: "Good",
    location: "Main Station - Equipment Room B",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2009,
    item_name: "Thermal Camera - Firefighting",
    category: "Heavy Equipment",
    quantity: 5,
    condition: "Good",
    location: "Main Station - Equipment Room B",
    status: "Available",
    threshold: 2,
    expire_date: null,
  },
  {
    item_ID: 2010,
    item_name: "Light Tower - Portable 4x1000W",
    category: "Heavy Equipment",
    quantity: 7,
    condition: "Good",
    location: "Main Station - Equipment Room C",
    status: "Available",
    threshold: 2,
    expire_date: null,
  },

  // ========== COMMUNICATION EQUIPMENT (Max: 50 units) ==========
  {
    item_ID: 2011,
    item_name: "Radio - Two-Way Handheld",
    category: "Communication Equipment",
    quantity: 35,
    condition: "Good",
    location: "Main Station - Equipment Room B",
    status: "Available",
    threshold: 10,
    expire_date: null,
  },
  {
    item_ID: 2012,
    item_name: "Radio - Vehicle Mounted",
    category: "Communication Equipment",
    quantity: 15,
    condition: "Good",
    location: "Main Station - Equipment Room B",
    status: "Available",
    threshold: 5,
    expire_date: null,
  },
  {
    item_ID: 2013,
    item_name: "Radio Repeater - Base Station",
    category: "Communication Equipment",
    quantity: 3,
    condition: "Good",
    location: "Main Station - Communication Tower",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2014,
    item_name: "Siren - Emergency Electronic",
    category: "Communication Equipment",
    quantity: 12,
    condition: "Good",
    location: "Main Station - Equipment Room B",
    status: "Available",
    threshold: 3,
    expire_date: null,
  },
  {
    item_ID: 2015,
    item_name: "Battery - Radio Rechargeable Pack",
    category: "Communication Equipment",
    quantity: 50,
    condition: "Good",
    location: "Main Station - Equipment Room B",
    status: "Available",
    threshold: 20,
    expire_date: new Date("2027-12-31"),
  },

  // ========== SAFETY EQUIPMENT (Max: 200 units) ==========
  {
    item_ID: 2016,
    item_name: "Traffic Cone - 28 Inch Orange",
    category: "Safety Equipment",
    quantity: 100,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 30,
    expire_date: null,
  },
  {
    item_ID: 2017,
    item_name: "Warning Light - LED Strobe",
    category: "Safety Equipment",
    quantity: 50,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 15,
    expire_date: null,
  },
  {
    item_ID: 2018,
    item_name: "Caution Tape - Yellow/Black",
    category: "Safety Equipment",
    quantity: 80,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 25,
    expire_date: null,
  },
  {
    item_ID: 2019,
    item_name: "Safety Barrier - Collapsible Metal",
    category: "Safety Equipment",
    quantity: 40,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 10,
    expire_date: null,
  },
  {
    item_ID: 2020,
    item_name: "Reflective Vest - High Visibility",
    category: "Safety Equipment",
    quantity: 60,
    condition: "Good",
    location: "Main Station - PPE Storage",
    status: "Available",
    threshold: 15,
    expire_date: null,
  },

  // ========== CLEANING SUPPLIES (Max: 500 units) ==========
  {
    item_ID: 2021,
    item_name: "Disinfectant - Spray 500ml",
    category: "Cleaning Supplies",
    quantity: 120,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 40,
    expire_date: new Date("2026-12-31"),
  },
  {
    item_ID: 2022,
    item_name: "Mop - Industrial with Bucket",
    category: "Cleaning Supplies",
    quantity: 15,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 5,
    expire_date: null,
  },
  {
    item_ID: 2023,
    item_name: "Trash Bags - Heavy Duty 50 Pack",
    category: "Cleaning Supplies",
    quantity: 60,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 20,
    expire_date: null,
  },
  {
    item_ID: 2024,
    item_name: "Glass Cleaner - 1 Liter",
    category: "Cleaning Supplies",
    quantity: 45,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 15,
    expire_date: new Date("2026-09-30"),
  },
  {
    item_ID: 2025,
    item_name: "Floor Cleaner - Industrial 5L",
    category: "Cleaning Supplies",
    quantity: 30,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 10,
    expire_date: new Date("2026-11-30"),
  },
  {
    item_ID: 2026,
    item_name: "Cleaning Cloth - Microfiber Pack",
    category: "Cleaning Supplies",
    quantity: 80,
    condition: "Good",
    location: "Main Station - Storage Room",
    status: "Available",
    threshold: 25,
    expire_date: null,
  },

  // ========== OFFICE SUPPLIES (Max: 1000 units) ==========
  {
    item_ID: 2027,
    item_name: "Paper - A4 Copy Ream",
    category: "Office Supplies",
    quantity: 150,
    condition: "Good",
    location: "Main Station - Office Storage",
    status: "Available",
    threshold: 50,
    expire_date: null,
  },
  {
    item_ID: 2028,
    item_name: "Pen - Ballpoint Blue Box",
    category: "Office Supplies",
    quantity: 200,
    condition: "Good",
    location: "Main Station - Office Storage",
    status: "Available",
    threshold: 60,
    expire_date: null,
  },
  {
    item_ID: 2029,
    item_name: "Folder - Manila Letter Size",
    category: "Office Supplies",
    quantity: 180,
    condition: "Good",
    location: "Main Station - Office Storage",
    status: "Available",
    threshold: 50,
    expire_date: null,
  },
  {
    item_ID: 2030,
    item_name: "Stapler - Heavy Duty",
    category: "Office Supplies",
    quantity: 25,
    condition: "Good",
    location: "Main Station - Office Storage",
    status: "Available",
    threshold: 8,
    expire_date: null,
  },
  {
    item_ID: 2031,
    item_name: "Sticky Notes - 3x3 Pack",
    category: "Office Supplies",
    quantity: 120,
    condition: "Good",
    location: "Main Station - Office Storage",
    status: "Available",
    threshold: 40,
    expire_date: null,
  },
  {
    item_ID: 2032,
    item_name: "Marker - Whiteboard Assorted",
    category: "Office Supplies",
    quantity: 90,
    condition: "Good",
    location: "Main Station - Training Room",
    status: "Available",
    threshold: 30,
    expire_date: null,
  },
  {
    item_ID: 2033,
    item_name: "Clipboard - Letter Size",
    category: "Office Supplies",
    quantity: 40,
    condition: "Good",
    location: "Main Station - Office Storage",
    status: "Available",
    threshold: 15,
    expire_date: null,
  },

  // ========== BREATHING APPARATUS (Max: 50 units) ==========
  {
    item_ID: 2034,
    item_name: "SCBA - Self Contained Unit",
    category: "Breathing Apparatus",
    quantity: 20,
    condition: "Good",
    location: "Main Station - Equipment Room A",
    status: "Available",
    threshold: 8,
    expire_date: null,
  },
  {
    item_ID: 2035,
    item_name: "Air Cylinder - SCBA 4500 PSI",
    category: "Breathing Apparatus",
    quantity: 45,
    condition: "Good",
    location: "Main Station - Equipment Room A",
    status: "Available",
    threshold: 15,
    expire_date: new Date("2028-12-31"),
  },
  {
    item_ID: 2036,
    item_name: "Face Mask - SCBA Standard",
    category: "Breathing Apparatus",
    quantity: 30,
    condition: "Good",
    location: "Main Station - Equipment Room A",
    status: "Available",
    threshold: 10,
    expire_date: null,
  },
  {
    item_ID: 2037,
    item_name: "Regulator - SCBA Assembly",
    category: "Breathing Apparatus",
    quantity: 25,
    condition: "Good",
    location: "Main Station - Equipment Room A",
    status: "Available",
    threshold: 8,
    expire_date: null,
  },
  {
    item_ID: 2038,
    item_name: "Escape Hood - Emergency",
    category: "Breathing Apparatus",
    quantity: 35,
    condition: "Good",
    location: "Main Station - Equipment Room A",
    status: "Available",
    threshold: 12,
    expire_date: new Date("2027-06-30"),
  },

  // ========== TRAINING EQUIPMENT (Max: 30 units) ==========
  {
    item_ID: 2039,
    item_name: "Training Manikin - CPR Adult",
    category: "Training Equipment",
    quantity: 8,
    condition: "Good",
    location: "Main Station - Training Room",
    status: "Available",
    threshold: 3,
    expire_date: null,
  },
  {
    item_ID: 2040,
    item_name: "Fire Simulator - Propane",
    category: "Training Equipment",
    quantity: 3,
    condition: "Good",
    location: "Main Station - Training Ground",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
  {
    item_ID: 2041,
    item_name: "Rescue Dummy - 165 Pounds",
    category: "Training Equipment",
    quantity: 6,
    condition: "Good",
    location: "Main Station - Training Ground",
    status: "Available",
    threshold: 2,
    expire_date: null,
  },
  {
    item_ID: 2042,
    item_name: "Training Cones - Set of 20",
    category: "Training Equipment",
    quantity: 12,
    condition: "Good",
    location: "Main Station - Training Ground",
    status: "Available",
    threshold: 4,
    expire_date: null,
  },
  {
    item_ID: 2043,
    item_name: "Ladder Props - Training Set",
    category: "Training Equipment",
    quantity: 4,
    condition: "Good",
    location: "Main Station - Training Ground",
    status: "Available",
    threshold: 1,
    expire_date: null,
  },
];

// Function to seed new categories
const seedNewCategories = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.DB_URI);
    console.log("✅ Connected to MongoDB");

    // Check if any items already exist (by checking item_ID range)
    const existingItem = await Inventory.findOne({
      item_ID: { $gte: 2001, $lte: 2053 }
    });

    if (existingItem) {
      console.log("⚠️  New category items already exist in database");
      console.log("   To re-seed, first delete items with item_ID 2001-2053");
      process.exit(0);
    }

    // Insert new items
    const result = await Inventory.insertMany(newCategoryItems);
    console.log(`✅ Successfully seeded ${result.length} new items across 8 categories`);
    console.log("   Categories added:");
    console.log("   - Vehicles: 15 items");
    console.log("   - Heavy Equipment: 5 items");
    console.log("   - Communication Equipment: 5 items");
    console.log("   - Safety Equipment: 5 items");
    console.log("   - Cleaning Supplies: 6 items");
    console.log("   - Office Supplies: 7 items");
    console.log("   - Breathing Apparatus: 5 items");
    console.log("   - Training Equipment: 5 items");
    console.log("   Total: 53 new items (item_ID: 2001-2053)");

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding new categories:", error);
    process.exit(1);
  }
};

// Run seeder
seedNewCategories();
